[package]
name = "bevy_seedling"
version = "0.2.0"
edition = "2021"
rust-version = "1.83.0"
license = "MIT OR Apache-2.0"
authors = ["Corvus Prudens <corvusprudens@gmail.com>"]
description = "A sprouting integration of the Firewheel audio engine"
readme = "README.md"
repository = "https://github.com/corvusprudens/bevy_seedling"
documentation = "https://docs.rs/bevy_seedling"
keywords = ["gamedev", "audio", "bevy", "firewheel"]
categories = ["game-development", "multimedia::audio"]
exclude = ["/assets"]

[features]
default = ["stream"]
stream = ["firewheel/stream_nodes"]
mp3 = ["symphonia/mp3"]
ogg = ["symphonia/ogg"]
profiling = []

[dependencies]
bevy_reflect = { version = "0.15" }
bevy_ecs = "0.15"
bevy_app = "0.15"
bevy_utils = "0.15"
bevy_log = "0.15"
bevy_hierarchy = "0.15"
bevy_asset = "0.15"
bevy_math = "0.15"
bevy_transform = "0.15"
firewheel = { path = "firewheel", features = ["bevy", "spatial_basic_node"] }
symphonium = "0.4"
symphonia = "0.5"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.13"
arrayvec = "0.7"
seedling_macros = { path = "./seedling_macros", version = "0.1.0" }

[dev-dependencies]
bevy = { version = "0.15", default-features = false, features = [
  "bevy_debug_stepping",
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_state",
  "multi_threaded",
  "sysinfo_plugin",
] }
criterion = "0.5"

[[bench]]
name = "basic"
harness = false
required-features = ["profiling"]
