[package]
name = "bevy_seedling"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy_reflect = { version = "0.15" }
bevy_ecs = "0.15"
bevy_app = "0.15"
bevy_utils = "0.15"
bevy_log = "0.15"
bevy_hierarchy = "0.15"
bevy_asset = "0.15"
bevy_math = "0.15"
firewheel = { git = "https://github.com/BillyDM/Firewheel.git" }
symphonium = "0.2.2"
symphonia = "0.5"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.13"
arrayvec = "0.7"
seedling_macros = { path = "./seedling_macros" }


[dev-dependencies]
bevy = { version = "0.15", default-features = false, features = [
  "bevy_debug_stepping",
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_state",
  "multi_threaded",
  "sysinfo_plugin",
] }
